# Generated by Django 4.0 on 2021-12-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='product',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
