# Generated by Django 4.0 on 2021-12-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_quantity_delete_ordereditems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='order_item',
            new_name='item',
        ),
    ]
